name: Run Unit Tests
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[dev]
#      - name: Lint
#        run: |
#          pylint falcano tests/**/*.py
      - name: Unit
        env:
          DYNAMODB_TABLE: unit-test-table
        run: python -m pytest -vvv --cov=falcano tests/unit